# Generated by Django 2.1.2 on 2018-10-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentClubWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date_purchased',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='market_exchange',
            field=models.CharField(choices=[('nasdaq', 'NASDAQ'), ('nyse', 'NYSE')], default='nasdaq', max_length=10),
        ),
    ]
