# Generated by Django 2.1.2 on 2018-10-20 22:40

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('InvestmentClubWeb', '0002_auto_20181020_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_purchased', models.DateField(verbose_name='Date Purchased')),
                ('shares', models.IntegerField(verbose_name='Number of Shares owned')),
                ('avg_cost_per_share', models.FloatField(verbose_name='Average Cost per Share')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('join_date', models.DateField(verbose_name='Date Joined')),
            ],
            options={
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='stock',
            name='cost_per_share',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='date_purchased',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='shares',
        ),
    ]
