# Generated by Django 2.1.2 on 2018-10-20 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentClubWeb', '0004_auto_20181020_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='join_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date Joined'),
        ),
    ]
