# Generated by Django 2.1.2 on 2018-10-21 03:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentClubWeb', '0005_auto_20181020_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_purchased', models.DateField(default=datetime.date.today, verbose_name='Date Purchased')),
                ('shares', models.IntegerField(default=0, verbose_name='Number of Shares owned')),
                ('cost_per_share', models.FloatField(default=0.0, verbose_name='Cost per Share')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvestmentClubWeb.Stock')),
            ],
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
