# Generated by Django 2.1.2 on 2018-10-21 03:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentClubWeb', '0006_auto_20181021_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.date.today, verbose_name='Date of Activity')),
            ],
        ),
    ]
