# Generated by Django 2.1.2 on 2018-10-21 03:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentClubWeb', '0007_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.date.today, verbose_name='Date of Activity')),
                ('notes', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Ledgers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=160)),
            ],
        ),
        migrations.DeleteModel(
            name='Ledger',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='credit_ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_ledger', to='InvestmentClubWeb.Ledgers'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='debit_ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_ledger', to='InvestmentClubWeb.Ledgers'),
        ),
    ]
