# Generated by Django 2.1.2 on 2018-10-21 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentClubWeb', '0008_auto_20181021_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Cash', max_length=160)),
            ],
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='credit_ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_ledger', to='InvestmentClubWeb.Ledger'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='debit_ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_ledger', to='InvestmentClubWeb.Ledger'),
        ),
        migrations.DeleteModel(
            name='Ledgers',
        ),
    ]
