# Generated by Django 2.1.2 on 2018-10-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentClubWeb', '0009_auto_20181021_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='name',
            field=models.CharField(default='cash', max_length=160),
        ),
    ]
