# Site settings
title: Cypress Investment Club
email: web@cyic.club
description: > # this means to ignore newlines until "baseurl:"
  Cypress Investment Club
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://cyic.club" # the base hostname & protocol for your site

twitter_username: cypressinvclub
github_username: cyic

# Build settings
markdown: kramdown
