# Site settings
title: Cypress Investment Club
email: test@example.com
description: > # this means to ignore newlines until "baseurl:"
  Cypress Investment Club
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://example.com" # the base hostname & protocol for your site

twitter_username: example
github_username: example

# Build settings
markdown: kramdown
